import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from generators.h5_generator import decorate_markdown_with_theme
from wanyou.synthesizer import build_augmented_markdown


def main():
    parser = argparse.ArgumentParser(description="Apply Wanyou LLM filtering and summaries to raw Markdown.")
    parser.add_argument("raw_markdown", help="Path to raw Markdown generated by crawler modules.")
    parser.add_argument("--output", "-o", default="", help="Final Markdown output path.")
    parser.add_argument("--no-theme", action="store_true", help="Skip Wanyou theme decoration.")
    args = parser.parse_args()

    raw_path = pathlib.Path(args.raw_markdown).resolve()
    output_path = pathlib.Path(args.output).resolve() if args.output else raw_path.with_name(raw_path.stem.replace("_raw", "") + ".md")
    raw_text = raw_path.read_text(encoding="utf-8")
    final_text = build_augmented_markdown(raw_text, current_markdown_path=str(raw_path))
    if not args.no_theme:
        final_text = decorate_markdown_with_theme(final_text, str(output_path))
    output_path.write_text(final_text, encoding="utf-8")
    print(f"final_markdown_path: {output_path}")


if __name__ == "__main__":
    main()
